README.md
This PR sets up travis CI in the project and adds a badge on readme. 
For more info on Travis, please visit https://travis-ci.org
=> ch: added travis badge

README.md, app.json
This PR adds heroku to the project, and also adds a heroku badge to readme.
- Heroku deployment: https://greenpot-api.herokuapp.com
Further information about Heroku deployment can be found here: https://herokuapp.com
=> Added heroku config and heroku badge

.sequelizerc, .travis.yml, src/models/index.js
This pr adds sequelize database ORM to the project
=> Addes sequelize config

.dockerignore, Dockerfile, docker-compose.yml, src/models/index.js
This pr adds a docker container for the project to be run inside
=> Added docker setup

package-lock.json, package.json, src/index.js, src/routes/auth.js, src/routes/index.js, swagger.json
This PR creates express routing for project, and also adds swagger documentation. With this, the Heroku build should also have the swagger docs on deployment.
=> Added Routing and Swagger Docs

README.md, package-lock.json, package.json, src/test/index.js
###PR Overview
This PR edits a few files on project to reflect GitHub organisation name change.
=> Edited project due to github changes

package.json, src/controllers/authController.js, src/controllers/index.js, src/middlewares/authMiddleware.js, src/middlewares/index.js, src/migrations/20191003092617-create-user.js, src/models/index.js, src/models/user.js, src/routes/auth.js, src/services/index.js, src/services/userService.js, src/test/auth.test.js, src/test/dummyData.js, src/utils/apiError.js, src/utils/index.js, src/utils/toolbox.js, src/utils/validationData.js, src/validations/authValidation.js, src/validations/index.js, swagger.json
This PR adds a user signup feature to the application
Also added
- user service
- middleware
- user validation
- user controller
- user tests
- - Run `npm run migrate:reset` && `npm run migrate` to create tables in your 
- Launch `http://localhost:3000/v1.0/api/auth/signup`on Postman
=> Added user signup

src/controllers/authController.js, src/middlewares/authMiddleware.js, src/routes/auth.js, src/test/auth.test.js, src/validations/authValidation.js
This PR adds a user Login feature to the application
Also added
- login middleware
- user login validation
- user login controller
- user tests
- - Run `npm run migrate:reset` && `npm run migrate` to create tables in your 
- Launch `http://localhost:3000/v1.0/api/auth/login`on Postman
=> Added user login

swagger.json
This PR edits the swagger docs for login.
=> ch: edited swagger

src/controllers/authController.js, src/middlewares/authMiddleware.js, src/routes/auth.js, src/services/userService.js, src/test/auth.test.js, src/utils/index.js, src/utils/mailer.js, src/utils/toolbox.js
This PR adds a user email verification feature upon signup. When a user signs up, he is sent a verification email to his account
Also added
- service to update user table given a key
- mailer class for sendgrid methods
- verification route
- - Run `npm run migrate:reset` && `npm run migrate` to create tables in your 
- Launch `http://localhost:3000/v1.0/api/auth/signup`on Postman
- …
=> Added user email verification

src/controllers/index.js, src/controllers/userController.js, src/middlewares/index.js, src/middlewares/userMiddleware.js, src/routes/index.js, src/routes/user.js, src/test/dummyData.js, src/test/user.test.js, src/utils/index.js, src/validations/index.js, src/validations/profileValidation.js, swagger.json
This PR adds a user update profile feature
Also added
- profile update validation
- user profile update middleware
- user profile update controller
- user tests
- - Run `npm run migrate:reset` && `npm run migrate` to create tables in your 
- Launch `http://localhost:3000/v1.0/api/user/profile/{id}`on Postman, make sure a user is already logged in with his/her token in the cookies.
- input …
=> ft: Added user profile update

src/controllers/authController.js, src/controllers/userController.js, src/middlewares/authMiddleware.js, src/middlewares/userMiddleware.js, src/routes/user.js, src/utils/mailer.js, src/validations/profileValidation.js
- This PR implements a feature to allow users to update their emails while logged in
- Plan out the algorithm for the feature
- Create route
- Implement authentication, verification and validation middleware
- Create a controller
- Clone the repo
- Navigate to the terminal and type `npm run start:dev`
- Open postman and then signup a new user and verify the email using the generated email verification link
- To update your email send a PATCH request to the endpoint `localhost:3000/v1.0/api/user/profile/email`. The request body should have a property "email", which is the new email
- A verification email will be sent which should be used to verify the profile
Algorithm for email update from profile
. User sends a request for an email update
. Check if the user is verified, if not respond …
=> implement feature for users to update their emails

src/controllers/ingredietController.js, src/middlewares/ingredientMiddleware.js, src/routes/ingredient.js, src/services/ingredientService.js, src/test/dummyData.js, src/test/ingredient.test.js, src/validations/ingredientValidation.js, swagger.json
This PR adds features to allow an admin to get, delete, and edit ingredients from the database
Roles
- Admin
- user
Also added
-  admin validations
- routes for get/edit/delete
- created ingredients controllers
- edited swagger docs
- user tests
- request sent to route
- request body contains the edit data: name and units 
- verification and authentications are carried out
- soft validations carried on on body object (no required)
- check if ingredient with name exists in database
- edit ingredient via controller
- check verifications and authentications
- get all ingredients via controller
- request sent to route
- request body contains the edit data: name and units 
- verification and authentications are carried out
- check if ingredient with name exists in database
- delete ingredient …
=> Admin can get / edit / delete Ingredient  

src/controllers/index.js, src/controllers/mealController.js, src/middlewares/index.js, src/middlewares/mealMiddleware.js, src/migrations/20191023082954-create-meal.js, src/migrations/20191023083549-create-mealIngredient.js, src/models/ingredient.js, src/models/meal.js, src/models/mealIngredient.js, src/routes/index.js, src/routes/meal.js, src/services/index.js, src/services/mealService.js, src/test/dummyData.js, src/test/ingredient.test.js, src/test/meal.test.js, src/validations/index.js, src/validations/mealValidation.js, swagger.json
This PR adds features to allow an admin to add meals and add ingredients to meals and get all meals
Roles
- Admin
- user
Also added
-  admin validations
- routes for add meals and ingredients, 
- created meal controllers, services
- edited swagger docs
- user tests
- Request sent to add a new meal into the database.
- The request is sent through the route and the user is authenticated (to make sure he / she is an admin). 
- The meal data is validated for input errors. 
- After validation via middleware, the data is sent via a model service to the database.
- the parameters are sent as an object
- the values are taken from the body and are validated for accuracy
- a check in the middleware for if that particular ingredient has been paid with the meal
- Add ingredient to meal.
- Clone the …
=> Added Meal features

src/controllers/mealController.js, src/middlewares/mealMiddleware.js, src/routes/meal.js, src/services/mealService.js, src/test/dummyData.js, src/test/meal.test.js, src/validations/mealValidation.js, swagger.json
- Implements the feature to allow admins to remove ingredients from meals
- Come up with the algorithm
- Implement, route, authentication, validations, and controller
- a meal with its ingredients should aready have been created
- send a `delete` request to the endpoint `/v1.0/api/v1/meal/:mealId/ingredient/:ingredientId`
- the `mealId` and `ingredientId` parameters should be provided to remove the ingredient from the specified meal
- a delete request is made to an endpoint with the mealId and ingredient Id in the params
- check if the meal exists, if not respond with an error
- check if the ingredient exists, if not respond with an error
- remove from meal ingredients the rows where mealId and ingredientId match the req params
=> implement feature to remove ingredients from meals

src/controllers/mealController.js, src/middlewares/mealMiddleware.js, src/routes/meal.js, src/services/categoryService.js, src/test/meal.test.js, swagger.json
- Implements the feature to allow admins to remove meals from meal ingredients
- Come up with the algorithm
- Implement, route, authentication, validations, and controller
- a meal with its ingredients should already have been created
- send a `delete` request to the endpoint `/v1.0/api/v1/meal/category/:categoryId/meal/:mealId`
- the `mealId` and `categoryId` parameters should be provided to remove the meal from the specified meal category
- a delete request is made to an endpoint with the mealId and category Id in the params
- check if the meal exists, if not respond with an error
- check if the meal category exists, if not respond with an error
- remove from meal category the rows where mealId and categoryId match the req params
=> Admin can delete meal from a Category

src/controllers/mealController.js, src/middlewares/mealMiddleware.js, src/routes/meal.js, src/test/meal.test.js, src/validations/mealValidation.js, swagger.json
- implements a feature to allow admins delete a meal
- develop alogrithm
- setup route. authentication, validation and controller
- write tests
- update swagger doc
- log in as an admin
- create a meal and take note of the id returned
- on postman send a `DELETE` request to the endpoint `/v1.0/api/meal/:mealId` to delete the meal
- `mealId` is the `id` of the created meal
- send in a delete request with the meal id in the parameters
- validate the meal id to ensure its an integer and that the meal exists
- delete the meal
=> implement feature to delete a meal

src/controllers/authController.js, src/controllers/mealController.js, src/middlewares/ingredientMiddleware.js, src/middlewares/mealMiddleware.js, src/routes/meal.js, src/test/meal.test.js, src/validations/mealValidation.js, swagger.json
- Implements the feature to allow admins to remove meal category
- Come up with the algorithm
- Implement, route, authentication, validations, and controller
- a meal category should be present in the database
- send a `delete` request to the endpoint `/v1.0/api/v1/meal/category/:id`
- the `id`  parameters should be provided to remove the meal category
- a delete request is made to an endpoint with the category Id in the params
- check if the meal category exists, if not respond with an error
- remove from meal category  from the category table
=> Admin can remove a category

src/routes/meal.js
This PR adds features to allow a user to get all meals
-`http://localhost:3000/v1.0/api/meal/` 
=> User can get meal

src/controllers/mealController.js, src/middlewares/mealMiddleware.js, src/routes/meal.js, src/services/categoryService.js, src/test/meal.test.js, src/validations/mealValidation.js, swagger.json
This PR adds features to allow a user to get meals by category
-`http://localhost:3000/v1.0/api/meal/category?category={value}` 
=> Added user can get meal by category

src/controllers/index.js, src/controllers/orderController.js, src/middlewares/index.js, src/middlewares/orderMiddleware.js, src/migrations/20191125101452-create-order.js, src/migrations/20191125101641-create-order-meal.js, src/models/meal.js, src/models/order.js, src/models/ordermeal.js, src/routes/index.js, src/routes/order.js, src/services/index.js, src/services/mealService.js, src/services/orderService.js, src/test/order.test.js, src/utils/toolbox.js, src/validations/index.js, src/validations/orderValidation.js, swagger.json
- Implements the feature to allow to place an order
- Setup routes, middleware and controllers, tables and relations
- Implement algorithm
- Test with postman
- Write unit tests
- Send a post request to the order endpoint
- Validate the request to ensure that the request body follows the appropriate format
- Check if the meal requested exists, respond appropriately if it doesnt
- Calculate the total price of the order
- Using a transaction add the `order` and the corresponding `order meals` to their respective tables
- Respond approproately
- A `POST` request to the endpoint `/order` should be made with the request body following the schema below:
`
meals : [{ mealId: Integer!, quantity: Integer! }, ...]
`
- The `mealId` will be the id of the meal to be ordered and the `quantity` is the …
=> A User Can Order Meals

src/controllers/cartController.js, src/controllers/index.js, src/controllers/orderController.js, src/middlewares/cartMiddleware.js, src/middlewares/index.js, src/migrations/20191206090414-create-cart.js, src/models/cart.js, src/routes/cart.js, src/routes/index.js, src/services/cartService.js, src/services/index.js, src/test/cart.test.js, src/test/meal.test.js, src/utils/toolbox.js, src/validations/orderValidation.js, swagger.json
- Implements the feature to allow users add meal to a cart
- Setup routes, middleware and controllers, tables and relations
- Implement algorithm
- Test with postman
- Write unit tests
- Send a post request to the cart endpoint
- Validate the request to ensure that the request body follows the appropriate format
- Check if the meal requested exists, respond appropriately if it doesn't
- Add meal/meals to cart
- Send a get request to the cart endpoint
- Validate the request to ensure that the request body follows the appropriate format
-  Calculate the total price of the order
- send meals to user, including price.
- Send a patch request to the cart endpoint
- Validate the request to ensure that the request body follows the appropriate format
- update meal quantity on patch
- Send a delete …
=> Added cart

package-lock.json, package.json, src/controllers/index.js, src/controllers/payController.js, src/routes/index.js, src/routes/pay.js, src/test/dummyData.js, src/test/payment.test.js, src/utils/index.js, src/utils/payments.js
- Implements the feature to allow users pay for meals in cart via paystack, using its initiate pay api (standard).
Descriptive docs for [paystack standard](https://developers.paystack.co/reference#paystack-standard-x)
- Setup routes and pay controllers
- Implement algorithm for calculating price via cart items
- Test with postman
- Write unit tests
- Initialise paystack get route
- Calculate price of meals in cart with quantity reflected
- Call paystack module  and pass in user `email` and `amount in kobo`
- retrieve paystack unique reference url in format `https://checkout.paystack.com/[access_code]`
- send url to frontend via json body.
To make sure the paystack api is not called after every `npm test`, the pivotal code is commented out for now and will be used only during production. …
=> Added paystack payment

package-lock.json, src/controllers/authController.js
Pulled the properties needed from the request body as opposed to directly inserting the request body details in the database to prevent malicious requests
=> Handle sign up request to prevent malicious intent

package.json, src/controllers/orderController.js, src/controllers/payController.js, src/routes/order.js, src/services/orderService.js, src/test/order.test.js
This PR adds features to allow admin to get all orders
-`http://localhost:3000/v1.0/api/order/` 
=> Admin can view all orders

package.json, src/controllers/orderController.js, src/routes/order.js, src/services/orderService.js, src/test/dummyData.js, src/test/order.test.js
This PR adds features to allow users to get their orders
-`http://localhost:3000/v1.0/api/order/` 
=> User view order

src/controllers/orderController.js, src/middlewares/cartMiddleware.js, src/middlewares/orderMiddleware.js, src/migrations/20200212141404-create-user-feedback.js, src/models/feedback.js, src/models/order.js, src/models/user.js, src/routes/order.js, src/services/orderService.js, src/test/order.test.js, src/validations/cartValidation.js, src/validations/index.js, src/validations/orderValidation.js
This PR adds features to allow user to get add feedback to order
-`http://localhost:3000/v1.0/api/order/[orderId]/feedback
- object
```
{
feedback: 'this is an amazing order I just made'
}
```
- make sure an admin is already logged in with his/her token in the cookies.
=> added user can add feedback to order

src/controllers/orderController.js, src/routes/order.js, src/services/orderService.js, src/test/order.test.js
This PR adds features to allow admin to get all order feedback
-`http://localhost:3000/v1.0/api/order/feedback` 
=> Admin view all order feedback

swagger.json
This PR updates swagger documentation
=> updated swagger
